server:
  port: 8080
spring:
  datasource:
    username: user
    password: 123456
    url: jdbc:mysql://localhost:13306/todo-list
  flyway:
    clean-on-validation-error: false
    locations: classpath:db/migration
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true